apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---	  
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: elasticsearch
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:7.3.0	  
        imagePullPolicy: IfNotPresent
#        resources:
#          limits:
#            cpu: 500m
#            memory: 2Gi
#          requests:
#            cpu: 500m
#            memory: 2Gi            
        ports:
        - containerPort: 9200	
        - containerPort: 9300	
        env:
        - name: discovery.type
          value: single-node  
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true		  
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: es-data-claim
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: es-data-claim
        persistentVolumeClaim:
          claimName: es-data-claim      
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
  namespace: default
spec:
  ports:
  - name: "9200"
    port: 9200
    targetPort: 9200
  - name: "9300"
    port: 9300
    targetPort: 9300	
  selector:
    app: elasticsearch
  sessionAffinity: None
  type: ClusterIP	  