apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-ws
  name: user-ws
  namespace: default
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate 
  selector:
    matchLabels:
      app: user-ws
  template:
    metadata:
      labels:
        app: user-ws
    spec:
      containers:
      - name: user-ws
        image: madhanbadridocker/users-microservice:0.0.2	  
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8014			
        env:
        - name: spring.profiles.active
          value: k8s
        - name: spring.rabbitmq.host
          value: rabbit-mq
        - name: spring.rabbitmq.username
          valueFrom:
            configMapKeyRef:
              key: spring.rabbitmq.username
              name: config-server-config
        - name: spring.rabbitmq.password
          valueFrom: 
            secretKeyRef:
              key: spring.rabbitmq.password
              name: config-server-secrets			  
        - name: spring.cloud.config.uri
          value: http://config-server:8012		
        volumeMounts:
        - name: api-logs-users
          mountPath: /api-logs
      - name: logstash
        image: madhanbadridocker/users-microservice-logstash:0.0.2	  
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5044	
        volumeMounts:
        - name: api-logs-users
          mountPath: /api-logs		
      volumes:
      - name: api-logs-users
        emptyDir: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-ws
  name: user-ws
  namespace: default
spec:
  ports:
  - name: "8014"
    port: 8014
    targetPort: 8014	
  selector:
    app: user-ws
  sessionAffinity: None
  type: ClusterIP	  